# Netlify configuration file
# Documentation: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command to run
  command = "npm run build"

  # Directory to publish (Vite outputs to 'dist' by default)
  publish = "dist"

  # Directory for Netlify Functions
  functions = "netlify/functions"

[build.environment]
  # Node version for builds
  NODE_VERSION = "20"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Allow inline scripts for Vite (needed for development)
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self' https://api.anthropic.com https://*.netlify.app; media-src 'self' blob:;"
